// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4L-7IeF-99jpZZ8HiyeIZR5VXlDFpONk',
    appId: '1:903685931258:web:0822f43d73964cde598943',
    messagingSenderId: '903685931258',
    projectId: 'kabbik-clone',
    authDomain: 'kabbik-clone.firebaseapp.com',
    storageBucket: 'kabbik-clone.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAst5_0tUlOkiPmqh5LWZEkMD6iwoK-dfQ',
    appId: '1:903685931258:android:37bc60d7c31abe1b598943',
    messagingSenderId: '903685931258',
    projectId: 'kabbik-clone',
    storageBucket: 'kabbik-clone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4AQ-_qo2ymPmaLOBl4aT3gbpSijCMBr4',
    appId: '1:903685931258:ios:01faef354aaec890598943',
    messagingSenderId: '903685931258',
    projectId: 'kabbik-clone',
    storageBucket: 'kabbik-clone.appspot.com',
    iosClientId: '903685931258-csd57ku5b2913eg5u0fgl7qdhuj0otf2.apps.googleusercontent.com',
    iosBundleId: 'com.example.kabbikUiClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4AQ-_qo2ymPmaLOBl4aT3gbpSijCMBr4',
    appId: '1:903685931258:ios:f8bb1bc8335278e2598943',
    messagingSenderId: '903685931258',
    projectId: 'kabbik-clone',
    storageBucket: 'kabbik-clone.appspot.com',
    iosBundleId: 'com.example.kabbikUiClone.RunnerTests',
  );
}
